### ISSUE TITLE
6.25更新Mac下闪退问题

### ISSUE THREAD

**Issue by pethame** [pokemonchw/dieloli#126]
Traceback (most recent call last):
  File "Script/Core/game_init.py", line 49, in init
  File "Script/Core/game_init.py", line 41, in run_main_flow
  File "Script/Design/start_flow.py", line 16, in start_frame
  File "Script/Design/handle_panel.py", line 18, in return_wrapper
  File "Script/UI/Flow/in_scene_flow.py", line 15, in in_scene_flow
  File "Script/UI/Panel/in_scene_panel.py", line 265, in draw
  File "Script/Core/flow_handle.py", line 278, in askfor_all
  File "Script/Core/flow_handle.py", line 198, in _cmd_deal
  File "Script/Core/flow_handle.py", line 121, in run_func
  File "Script/UI/Panel/in_scene_panel.py", line 389, in handle_instruct
  File "Script/Design/handle_instruct.py", line 48, in handle_instruct
  File "Script/Design/handle_instruct.py", line 64, in return_wrapper
  File "Script/Design/handle_instruct.py", line 137, in handle_chat
  File "Script/Design/update.py", line 13, in game_update_flow
  File "Script/Design/character_behavior.py", line 46, in init_character_behavior
  File "Script/Design/character_behavior.py", line 86, in character_behavior
  File "Script/Design/character_behavior.py", line 190, in judge_character_status
  File "Script/Design/settle_behavior.py", line 30, in handle_settle_behavior
  File "Script/Design/settle_behavior.py", line 153, in return_wrapper
  File "Script/Settle/default.py", line 1085, in handle_interrupt_target_activity
AttributeError: 'NoneType' object has no attribute 'draw'

测试系统：Catalina 10.15.7

**Comment by pokemonchw** [comment]
感谢反馈，已修复
