### ISSUE TITLE
python 无法打开， 找不到numpy

### ISSUE THREAD

**Issue by Lostangel13** [pokemonchw/dieloli#128]
Traceback (most recent call last):
  File "C:\Users\weish\Documents\Eragames\dieloli-master\game.py", line 13, in <module>
    from Script.Config import game_config, name_config
  File "C:\Users\weish\Documents\Eragames\dieloli-master\Script\Config\name_config.py", line 3, in <module>
    from Script.Core import json_handle, value_handle, cache_control, game_type, constant
  File "C:\Users\weish\Documents\Eragames\dieloli-master\Script\Core\value_handle.py", line 5, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

**Comment by Lostangel13** [comment]
是3.9.5版本

**Comment by Lostangel13** [comment]
双击game.py后黑了一下就退出了

**Comment by pokemonchw** [comment]
你没有安装依赖，依赖的安装详见readme，不过这里建议下载release里打包好的文件
