### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by 331986** [pokemonchw/dieloli#129]
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 49, in init
    run_main_flow()
  File "Script\Core\game_init.py", line 41, in run_main_flow
    main_flow()
  File "Script\Design\start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "Script\UI\Flow\in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "Script\UI\Panel\in_scene_panel.py", line 273, in draw
    flow_handle.askfor_all(ask_list)
  File "Script\Core\flow_handle.py", line 278, in askfor_all
    _cmd_deal(order)
  File "Script\Core\flow_handle.py", line 198, in _cmd_deal
    cmd_map[order_number]()
  File "Script\Core\flow_handle.py", line 121, in run_func
    cmd_func(*arg, **kw)
  File "Script\UI\Panel\in_scene_panel.py", line 398, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "Script\Design\handle_instruct.py", line 48, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "Script\Design\handle_instruct.py", line 64, in return_wrapper
    return func(*args, **kwargs)
  File "Script\Design\handle_instruct.py", line 84, in handle_rest
    update.game_update_flow(10)
  File "Script\Design\update.py", line 13, in game_update_flow
    character_behavior.init_character_behavior()
  File "Script\Design\character_behavior.py", line 46, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "Script\Design\character_behavior.py", line 86, in character_behavior
    status_judge = judge_character_status(character_id, now_time)
  File "Script\Design\character_behavior.py", line 190, in judge_character_status
    settle_draw = settle_behavior.handle_settle_behavior(character_id, end_time)
  File "Script\Design\settle_behavior.py", line 30, in handle_settle_behavior
    constant.settle_behavior_effect_data[effect_id](
  File "Script\Design\settle_behavior.py", line 157, in return_wrapper
    return func(*args, **kwargs)
  File "Script\Settle\default.py", line 1185, in handle_target_add_favorability_for_eloquence
    character_handle.add_favorability(
  File "Script\Design\character_handle.py", line 374, in add_favorability
    target_data.social_contact[now_social].remove(now_key)
KeyError: 0

**Comment by pokemonchw** [comment]
在 [pr 130](https://github.com/pokemonchw/dieloli/pull/130) 中尝试进行了修复，期待反馈

**Comment by pokemonchw** [comment]
新版本待测试
