### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Lostangel13** [pokemonchw/dieloli#131]
Traceback (most recent call last):
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Core\game_init.py", line 49, in init
    run_main_flow()
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Core\game_init.py", line 41, in run_main_flow
    main_flow()
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\UI\Flow\in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\UI\Panel\in_scene_panel.py", line 273, in draw
    flow_handle.askfor_all(ask_list)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Core\flow_handle.py", line 278, in askfor_all
    _cmd_deal(order)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Core\flow_handle.py", line 198, in _cmd_deal
    cmd_map[order_number]()
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Core\flow_handle.py", line 121, in run_func
    cmd_func(*arg, **kw)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\UI\Panel\in_scene_panel.py", line 398, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\handle_instruct.py", line 48, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\handle_instruct.py", line 64, in return_wrapper
    return func(*args, **kwargs)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\handle_instruct.py", line 493, in handle_play_guitar
    update.game_update_flow(10)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\update.py", line 13, in game_update_flow
    character_behavior.init_character_behavior()
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\character_behavior.py", line 46, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\character_behavior.py", line 82, in character_behavior
    character_target_judge(character_id, now_time)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\character_behavior.py", line 100, in character_target_judge
    target, _, judge = search_target(
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\character_behavior.py", line 252, in search_target
    premise_judge = handle_premise.handle_premise(premise, character_id)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\handle_premise.py", line 45, in handle_premise
    return constant.handle_premise_data[premise](character_id)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\handle_premise.py", line 2146, in handle_in_class_time
    judge,_unused,_unused,_unused,_unused = character.judge_character_in_class_time(character_id)
  File "C:\Users\weish\Documents\dieloli-master\dieloli-master\Script\Design\character.py", line 192, in judge_character_in_class_time
    return 1, school_id, now_week, timetable.class_times, timetable.course
UnboundLocalError: local variable 'school_id' referenced before assignment

**Comment by pokemonchw** [comment]
已在 [pr132](https://github.com/pokemonchw/dieloli/pull/132) 中修复
