### ISSUE TITLE
WIN10 闪退

### ISSUE THREAD

**Issue by ARA1226** [pokemonchw/dieloli#133]
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 49, in init
  File "Script\Core\game_init.py", line 41, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\in_scene_flow.py", line 15, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 273, in draw
  File "Script\Core\flow_handle.py", line 278, in askfor_all
  File "Script\Core\flow_handle.py", line 198, in _cmd_deal
  File "Script\Core\flow_handle.py", line 121, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 398, in handle_instruct
  File "Script\Design\handle_instruct.py", line 48, in handle_instruct
  File "Script\Design\handle_instruct.py", line 64, in return_wrapper
  File "Script\Design\handle_instruct.py", line 439, in handle_attend_class
  File "Script\Design\update.py", line 13, in game_update_flow
  File "Script\Design\character_behavior.py", line 46, in init_character_behavior
  File "Script\Design\character_behavior.py", line 82, in character_behavior
  File "Script\Design\character_behavior.py", line 100, in character_target_judge
  File "Script\Design\character_behavior.py", line 252, in search_target
  File "Script\Design\handle_premise.py", line 45, in handle_premise
  File "Script\Design\handle_premise.py", line 27, in return_wrapper
  File "Script\Design\handle_premise.py", line 2146, in handle_in_class_time
  File "Script\Design\character.py", line 192, in judge_character_in_class_time
UnboundLocalError: local variable 'school_id' referenced before assignment

**Comment by pokemonchw** [comment]
等我这几天忙完工作，过年前会做一次更新，重做了整个ai系统，这个bug我先不管了

**Comment by ARA1226** [comment]
好的 感谢你 辛苦了

**Comment by kinar0** [comment]
作者辛苦了

**Comment by pokemonchw** [comment]
新版本待测试
