### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Septembershadow** [pokemonchw/dieloli#164]
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 49, in init
  File "Script\Core\game_init.py", line 41, in run_main_flow
  File "Script\Design\start_flow.py", line 17, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\in_scene_flow.py", line 14, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 358, in draw
  File "Script\Core\flow_handle.py", line 279, in askfor_all
  File "Script\Core\flow_handle.py", line 199, in _cmd_deal
  File "Script\Core\flow_handle.py", line 122, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 492, in handle_instruct
  File "Script\Design\handle_instruct.py", line 46, in handle_instruct
  File "Script\Design\instruct\active.py", line 124, in handle_handle_in_handle
  File "Script\Design\update.py", line 43, in game_update_flow
  File "Script\Design\character_behavior.py", line 51, in init_character_behavior
  File "Script\Design\character_behavior.py", line 146, in run_character_target
  File "Script\StateMachine\pathfinding.py", line 34, in character_move_to_classroom
KeyError: -1
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 49, in init
  File "Script\Core\game_init.py", line 41, in run_main_flow
  File "Script\Design\start_flow.py", line 17, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\in_scene_flow.py", line 14, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 358, in draw
  File "Script\Core\flow_handle.py", line 279, in askfor_all
  File "Script\Core\flow_handle.py", line 199, in _cmd_deal
  File "Script\Core\flow_handle.py", line 122, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 492, in handle_instruct
  File "Script\Design\handle_instruct.py", line 46, in handle_instruct
  File "Script\Design\instruct\active.py", line 106, in handle_embrace
  File "Script\Design\update.py", line 43, in game_update_flow
  File "Script\Design\character_behavior.py", line 51, in init_character_behavior
  File "Script\Design\character_behavior.py", line 146, in run_character_target
  File "Script\StateMachine\pathfinding.py", line 34, in character_move_to_classroom
KeyError: -1
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 49, in init
  File "Script\Core\game_init.py", line 41, in run_main_flow
  File "Script\Design\start_flow.py", line 17, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\in_scene_flow.py", line 14, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 358, in draw
  File "Script\Core\flow_handle.py", line 279, in askfor_all
  File "Script\Core\flow_handle.py", line 199, in _cmd_deal
  File "Script\Core\flow_handle.py", line 122, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 492, in handle_instruct
  File "Script\Design\handle_instruct.py", line 46, in handle_instruct
  File "Script\Design\instruct\obscenity.py", line 61, in handle_stroke
  File "Script\Design\update.py", line 43, in game_update_flow
  File "Script\Design\character_behavior.py", line 51, in init_character_behavior
  File "Script\Design\character_behavior.py", line 146, in run_character_target
  File "Script\StateMachine\pathfinding.py", line 34, in character_move_to_classroom
KeyError: -1
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 49, in init
  File "Script\Core\game_init.py", line 41, in run_main_flow
  File "Script\Design\start_flow.py", line 17, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\in_scene_flow.py", line 14, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 358, in draw
  File "Script\Core\flow_handle.py", line 279, in askfor_all
  File "Script\Core\flow_handle.py", line 199, in _cmd_deal
  File "Script\Core\flow_handle.py", line 122, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 492, in handle_instruct
  File "Script\Design\handle_instruct.py", line 46, in handle_instruct
  File "Script\Design\instruct\study.py", line 68, in handle_attend_class
  File "Script\Design\update.py", line 34, in game_update_flow
  File "Script\Design\character_behavior.py", line 51, in init_character_behavior
  File "Script\Design\character_behavior.py", line 146, in run_character_target
  File "Script\StateMachine\pathfinding.py", line 453, in character_move_to_square
KeyError: -1

**Comment by pokemonchw** [comment]
https://github.com/pokemonchw/dieloli/commit/a97b14541626b4d333cf171ab92f1177795832d7 感谢反馈，已修复
