### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Septembershadow** [pokemonchw/dieloli#179]
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 49, in init
  File "Script\Core\game_init.py", line 41, in run_main_flow
  File "Script\Design\start_flow.py", line 17, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\in_scene_flow.py", line 14, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 133, in draw
  File "Script\UI\Panel\game_info_panel.py", line 71, in __init__
  File "Script\Design\game_time.py", line 553, in get_temperature
KeyError: 8

**Comment by pokemonchw** [comment]
看上去是某种未知的情况下气温没有被正确模拟造成的，我明天上班研究一下

**Comment by pokemonchw** [comment]
https://github.com/pokemonchw/dieloli/commit/399093434db52a95eac4cac35a5443fec0acf63b 已修正
