### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by woshiluo** [pokemonchw/dieloli#42]
在购买食品时，若物品只剩一个，则买完后再购买其他食品会触发如下报错

```shell
Exception in thread flowthread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/dieloli/Script/Core/game_init.py", line 57, in _init
    init(main_func)
  File "/tmp/dieloli/Script/Core/game_init.py", line 46, in init
    run_main_flow()
  File "/tmp/dieloli/Script/Core/game_init.py", line 39, in run_main_flow
    main_flow()
  File "/tmp/dieloli/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/tmp/dieloli/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/tmp/dieloli/Script/UI/Flow/food_shop_flow.py", line 15, in food_shop_flow
    now_panel.draw()
  File "/tmp/dieloli/Script/UI/Panel/food_shop_panel.py", line 44, in draw
    food_name_list = list(cooking.get_restaurant_food_type_list_buy_food_type(self.now_panel).items())
  File "/tmp/dieloli/Script/Design/cooking.py", line 361, in get_restaurant_food_type_list_buy_food_type
    now_food_uid = list(cache.restaurant_data[food_id].keys())[0]
IndexError: list index out of range
```

**Comment by pokemonchw** [comment]
感谢，已经在本周更新中修复
