### ISSUE TITLE
一天结束时发生ui界面闪退

### ISSUE THREAD

**Issue by starwing1981** [pokemonchw/dieloli#75]
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 50, in init
  File "Script\Core\game_init.py", line 42, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\in_scene_flow.py", line 15, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 76, in draw
  File "Script\UI\Panel\game_info_panel.py", line 49, in __init__
  File "Script\Design\game_time.py", line 299, in get_sun_time
KeyError: 16

**Comment by pokemonchw** [comment]
ummm这个看上去是旧存档的升级问题，我晚上更新的时候做一下兼容吧

**Comment by starwing1981** [comment]
这个问题是我开新档第一天结束时触发的。版本是已经编译的2021.4.18.5这个版本，希望这个信息对您有些帮助。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pokemonchw/dieloli] 一天结束时发生ui界面闪退 (#75)





 
ummm这个看上去是旧存档的升级问题，我晚上更新的时候做一下兼容吧

**Comment by pokemonchw** [comment]
好了～
