### ISSUE TITLE
创建角色完成时闪退

### ISSUE THREAD

**Issue by DumbMice** [pokemonchw/dieloli#78]
Bug描述：
创建角色阶段，在回答完所有问题后窗口直接闪退消失。

发生条件：
无论角色名中英文，或者直接随机属性都会发生此bug。

os:
Ubuntu 18.04.5 LTS
python 3.7.10, miniconda 4.10.1

命令：
在conda的虚拟环境下：
$ python -m pip install -r requirements.txt
$ python game.py

**Comment by DumbMice** [comment]
error.log 记录如下：

Traceback (most recent call last):
  File "/mnt/data/Fun/dieloli/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/mnt/data/Fun/dieloli/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/mnt/data/Fun/dieloli/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/mnt/data/Fun/dieloli/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/mnt/data/Fun/dieloli/Script/UI/Flow/creator_character_flow.py", line 41, in creator_character_panel
    game_start()
  File "/mnt/data/Fun/dieloli/Script/UI/Flow/creator_character_flow.py", line 56, in game_start
    course.init_class_time_table()
  File "/mnt/data/Fun/dieloli/Script/Design/course.py", line 67, in init_class_time_table
    for course in reversed(class_hour.keys()):
TypeError: 'dict_keys' object is not reversible
