### ISSUE TITLE
喝饮料崩溃？

### ISSUE THREAD

**Issue by DumbMice** [pokemonchw/dieloli#79]
在超市里买了牛奶，进食，吃面包零食没问题。点击饮品（还没有显示的时候）就崩溃了。

以下是error.log

Traceback (most recent call last):
  File "/mnt/data/Fun/dieloli/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/mnt/data/Fun/dieloli/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/mnt/data/Fun/dieloli/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/mnt/data/Fun/dieloli/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/mnt/data/Fun/dieloli/Script/UI/Flow/food_bag_flow.py", line 14, in food_bag_flow
    now_panel.draw()
  File "/mnt/data/Fun/dieloli/Script/UI/Panel/food_bag_panel.py", line 78, in draw
    yrn = flow_handle.askfor_all(return_list)
  File "/mnt/data/Fun/dieloli/Script/Core/flow_handle.py", line 253, in askfor_all
    _cmd_deal(order)
  File "/mnt/data/Fun/dieloli/Script/Core/flow_handle.py", line 170, in _cmd_deal
    cmd_map[order_number]()
  File "/mnt/data/Fun/dieloli/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/mnt/data/Fun/dieloli/Script/UI/Panel/food_bag_panel.py", line 91, in change_panel
    cooking.get_character_food_bag_type_list_buy_food_type(0, self.now_panel).items()
  File "/mnt/data/Fun/dieloli/Script/Design/cooking.py", line 315, in get_character_food_bag_type_list_buy_food_type
    and not food_config.fruit
UnboundLocalError: local variable 'food_config' referenced before assignment

**Comment by pokemonchw** [comment]
已修复
