### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by DoctorChen-Endless** [pokemonchw/dieloli#95]
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 265, in draw
    flow_handle.askfor_all(ask_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 388, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 115, in handle_see_attr
    now_draw.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/see_character_info_panel.py", line 1236, in draw
    self.handle_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/see_character_info_panel.py", line 1089, in draw
    yrn = flow_handle.askfor_all(self.return_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/see_character_info_panel.py", line 1199, in next_character
    now_index = self.character_list.index(self.character_id)
ValueError: 1028 is not in list
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/title_flow.py", line 52, in title_panel
    elif now_key == now_list[3]:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 265, in draw
    flow_handle.askfor_all(ask_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 388, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 136, in handle_chat
    update.game_update_flow(10)
  File "/home/endless/game/dieloli-master/Script/Design/update.py", line 13, in game_update_flow
    character_behavior.init_character_behavior()
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 45, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 81, in character_behavior
    character_target_judge(character_id, now_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 99, in character_target_judge
    target, _, judge = search_target(
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 234, in search_target
    premise_judge = handle_premise.handle_premise(premise, character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 45, in handle_premise
    return constant.handle_premise_data[premise](character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 96, in handle_in_breakfast_time
    now_time = game_time.get_sun_time(character_data.behavior.start_time)
  File "/home/endless/game/dieloli-master/Script/Design/game_time.py", line 329, in get_sun_time
    return cache.sun_phase[now_date_str][now_time.hour][now_time.minute]
KeyError: 13
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 265, in draw
    flow_handle.askfor_all(ask_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 388, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 187, in handle_touch_head
    update.game_update_flow(2)
  File "/home/endless/game/dieloli-master/Script/Design/update.py", line 11, in game_update_flow
    character_behavior.init_character_behavior()
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 45, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 85, in character_behavior
    status_judge = judge_character_status(character_id, now_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 179, in judge_character_status
    talk.handle_talk(character_id)
  File "/home/endless/game/dieloli-master/Script/Design/talk.py", line 43, in handle_talk
    now_add_weight = constant.handle_premise_data[premise](character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 96, in handle_in_breakfast_time
    now_time = game_time.get_sun_time(character_data.behavior.start_time)
  File "/home/endless/game/dieloli-master/Script/Design/game_time.py", line 329, in get_sun_time
    return cache.sun_phase[now_date_str][now_time.hour][now_time.minute]
KeyError: 14
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 265, in draw
    flow_handle.askfor_all(ask_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 388, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 316, in handle_touch_chest
    update.game_update_flow(10)
  File "/home/endless/game/dieloli-master/Script/Design/update.py", line 11, in game_update_flow
    character_behavior.init_character_behavior()
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 45, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 85, in character_behavior
    status_judge = judge_character_status(character_id, now_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 179, in judge_character_status
    talk.handle_talk(character_id)
  File "/home/endless/game/dieloli-master/Script/Design/talk.py", line 43, in handle_talk
    now_add_weight = constant.handle_premise_data[premise](character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 96, in handle_in_breakfast_time
    now_time = game_time.get_sun_time(character_data.behavior.start_time)
  File "/home/endless/game/dieloli-master/Script/Design/game_time.py", line 329, in get_sun_time
    return cache.sun_phase[now_date_str][now_time.hour][now_time.minute]
KeyError: 14
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/see_map_flow.py", line 14, in see_map_flow
    now_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/see_map_panel.py", line 168, in draw
    yrn = flow_handle.askfor_all(return_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/see_map_panel.py", line 334, in move_now
    character_move.own_charcter_move(scene_path)
  File "/home/endless/game/dieloli-master/Script/Design/character_move.py", line 29, in own_charcter_move
    update.game_update_flow(now_need_time)
  File "/home/endless/game/dieloli-master/Script/Design/update.py", line 11, in game_update_flow
    character_behavior.init_character_behavior()
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 45, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 85, in character_behavior
    status_judge = judge_character_status(character_id, now_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 179, in judge_character_status
    talk.handle_talk(character_id)
  File "/home/endless/game/dieloli-master/Script/Design/talk.py", line 43, in handle_talk
    now_add_weight = constant.handle_premise_data[premise](character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 96, in handle_in_breakfast_time
    now_time = game_time.get_sun_time(character_data.behavior.start_time)
  File "/home/endless/game/dieloli-master/Script/Design/game_time.py", line 329, in get_sun_time
    return cache.sun_phase[now_date_str][now_time.hour][now_time.minute]
KeyError: 14
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 265, in draw
    flow_handle.askfor_all(ask_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 388, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 136, in handle_chat
    update.game_update_flow(10)
  File "/home/endless/game/dieloli-master/Script/Design/update.py", line 13, in game_update_flow
    character_behavior.init_character_behavior()
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 45, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 81, in character_behavior
    character_target_judge(character_id, now_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 99, in character_target_judge
    target, _, judge = search_target(
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 234, in search_target
    premise_judge = handle_premise.handle_premise(premise, character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 45, in handle_premise
    return constant.handle_premise_data[premise](character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 96, in handle_in_breakfast_time
    now_time = game_time.get_sun_time(character_data.behavior.start_time)
  File "/home/endless/game/dieloli-master/Script/Design/game_time.py", line 329, in get_sun_time
    return cache.sun_phase[now_date_str][now_time.hour][now_time.minute]
KeyError: 2
Traceback (most recent call last):
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/endless/game/dieloli-master/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/endless/game/dieloli-master/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/UI/Flow/in_scene_flow.py", line 15, in in_scene_flow
    now_panel.draw()
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 265, in draw
    flow_handle.askfor_all(ask_list)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/home/endless/game/dieloli-master/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/home/endless/game/dieloli-master/Script/UI/Panel/in_scene_panel.py", line 388, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_instruct.py", line 83, in handle_rest
    update.game_update_flow(10)
  File "/home/endless/game/dieloli-master/Script/Design/update.py", line 13, in game_update_flow
    character_behavior.init_character_behavior()
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 45, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 81, in character_behavior
    character_target_judge(character_id, now_time)
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 99, in character_target_judge
    target, _, judge = search_target(
  File "/home/endless/game/dieloli-master/Script/Design/character_behavior.py", line 234, in search_target
    premise_judge = handle_premise.handle_premise(premise, character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 45, in handle_premise
    return constant.handle_premise_data[premise](character_id)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "/home/endless/game/dieloli-master/Script/Design/handle_premise.py", line 96, in handle_in_breakfast_time
    now_time = game_time.get_sun_time(character_data.behavior.start_time)
  File "/home/endless/game/dieloli-master/Script/Design/game_time.py", line 329, in get_sun_time
    return cache.sun_phase[now_date_str][now_time.hour][now_time.minute]
KeyError: 2

**Comment by pokemonchw** [comment]
新版本待测试
