### ISSUE TITLE
和Mac似乎不兼容

### ISSUE THREAD

**Issue by pethame** [pokemonchw/dieloli#96]
尝试做了Mac build：https://github.com/pethame/dieloli/blob/Past.2021.6.22.13/.github/workflows/python-app.yml

Build结果：https://github.com/pethame/dieloli/releases/tag/Past.2021.6.22.13

解决了Catalina系统下Python 3.7+一个由于从dist directory copy到dieloli directory造成的codesign问题。相关issue：https://github.com/pyinstaller/pyinstaller/issues/5062

但是最后build的成果还是有以下问题：

···
Traceback (most recent call last):
  File "game.py", line 9, in <module>
  File "Script/Config/normal_config.py", line 16, in init_normal_config
  File "configparser.py", line 960, in __getitem__
KeyError: 'game'
[876] Failed to execute script game
···

**Comment by pethame** [comment]
修好了。虽然表现为相对路径的问题，但其实应该是我本地python路径的问题。重装了pyinstaller和pip就somehow可以run了。
